# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
warnings_are_errors: false
sudo: required
cache: packages

before_install:
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
    - sudo apt-get --yes --force-yes update -qq
    - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev

r_binary_packages:
    - rgdal

env:
  global:
    - NOT_CRAN=true
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

notifications:
  email:
    on_success: change
    on_failure: change
