# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_deploy:
- R -e "install.packages('xml2', repos = 'http://cran.rstudio.com')"
