# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
    -ordel
dist: trusty
warnings_are_errors: false
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_packages:
    - sf

r_binary_packages:
    - rgdal

env:
  global:
    - NOT_CRAN=true
before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

notifications:
  email:
    on_success: change
    on_failure: change
